import 'dart:convert';

import 'package:http/http.dart' as http;

/// Result of a successful authentication with Hasura Auth.
class AuthResult {
  final String accessToken;
  final String? refreshToken;
  final String userId;
  final String? displayName;

  const AuthResult({
    required this.accessToken,
    this.refreshToken,
    required this.userId,
    this.displayName,
  });
}

/// Error from authentication attempt.
class AuthException implements Exception {
  final String message;
  final int? statusCode;

  const AuthException(this.message, {this.statusCode});

  @override
  String toString() => message;
}

/// Service for authenticating with Hasura Auth on an nSelf server.
///
/// Hasura Auth exposes sign-in at `/v1/signin/email-password` on the auth
/// subdomain, which nSelf proxies through nginx.
class AuthService {
  final http.Client _httpClient;

  AuthService({http.Client? httpClient})
      : _httpClient = httpClient ?? http.Client();

  /// Sign in with email and password against the nSelf server's Hasura Auth.
  ///
  /// [serverUrl] is the base URL (e.g. `https://api.example.com`).
  /// Hasura Auth lives at `{serverUrl}/v1/signin/email-password`.
  Future<AuthResult> signIn({
    required String serverUrl,
    required String email,
    required String password,
  }) async {
    final url = _authUrl(serverUrl, '/v1/signin/email-password');

    final http.Response response;
    try {
      response = await _httpClient.post(
        Uri.parse(url),
        headers: {'Content-Type': 'application/json'},
        body: jsonEncode({'email': email, 'password': password}),
      );
    } catch (e) {
      throw AuthException(
        'Could not reach server. Check the URL and your network connection.',
      );
    }

    if (response.statusCode == 200) {
      final body = jsonDecode(response.body) as Map<String, dynamic>;
      final session = body['session'] as Map<String, dynamic>?;
      final user = session?['user'] as Map<String, dynamic>?;

      final accessToken = session?['accessToken'] as String?;
      if (accessToken == null) {
        throw const AuthException('Server returned success but no access token.');
      }

      return AuthResult(
        accessToken: accessToken,
        refreshToken: session?['refreshToken'] as String?,
        userId: user?['id'] as String? ?? '',
        displayName: user?['displayName'] as String?,
      );
    }

    // Parse error message from Hasura Auth response.
    String errorMsg;
    try {
      final body = jsonDecode(response.body) as Map<String, dynamic>;
      errorMsg = body['message'] as String? ?? 'Authentication failed.';
    } catch (_) {
      errorMsg = 'Authentication failed (status ${response.statusCode}).';
    }

    throw AuthException(errorMsg, statusCode: response.statusCode);
  }

  /// Redeem a pairing code generated by the server's nclaw CLI or TG bot.
  ///
  /// [serverUrl] is the base URL (e.g. `https://api.example.com`).
  /// [code] accepts either the 6-char short code or the full 64-char token.
  ///
  /// Returns the [userId] associated with the pair code on success.
  /// Throws [AuthException] if the code is invalid, expired, or already used.
  Future<String> redeemPairCode({
    required String serverUrl,
    required String code,
  }) async {
    final url = _authUrl(serverUrl, '/claw/devices/pair/redeem');

    final http.Response response;
    try {
      response = await _httpClient.post(
        Uri.parse(url),
        headers: {'Content-Type': 'application/json'},
        body: jsonEncode({'token': code.toUpperCase().trim()}),
      );
    } catch (e) {
      throw AuthException(
        'Could not reach server. Check the URL and your network connection.',
      );
    }

    if (response.statusCode == 200) {
      final body = jsonDecode(response.body) as Map<String, dynamic>;
      final userId = body['user_id'] as String?;
      if (userId == null || userId.isEmpty) {
        throw const AuthException('Server returned success but no user ID.');
      }
      return userId;
    }

    if (response.statusCode == 429) {
      throw const AuthException(
        'Too many attempts. Wait 10 minutes and try again.',
        statusCode: 429,
      );
    }

    String errorMsg;
    try {
      final body = jsonDecode(response.body) as Map<String, dynamic>;
      errorMsg = body['error'] as String? ?? 'Invalid or expired pairing code.';
    } catch (_) {
      errorMsg = 'Invalid or expired pairing code (${response.statusCode}).';
    }

    throw AuthException(errorMsg, statusCode: response.statusCode);
  }

  /// Build the auth endpoint URL.
  /// nSelf proxies Hasura Auth through nginx at the server's base URL.
  String _authUrl(String serverUrl, String path) {
    // Remove trailing slash from server URL.
    final base = serverUrl.endsWith('/')
        ? serverUrl.substring(0, serverUrl.length - 1)
        : serverUrl;
    return '$base$path';
  }

  /// Submit an OAuth authorization code to the nself-claw plugin callback endpoint.
  ///
  /// Called by [OAuthScreen] after intercepting the redirect URI from the WebView.
  /// [service] is the provider name (e.g. 'google', 'anthropic', 'openai').
  static Future<void> submitOAuthCode({
    required String serverUrl,
    required String service,
    required String code,
    String? sessionId,
  }) async {
    final base = serverUrl.endsWith('/')
        ? serverUrl.substring(0, serverUrl.length - 1)
        : serverUrl;
    final resp = await http.post(
      Uri.parse('$base/claw/oauth/$service/callback'),
      headers: {'Content-Type': 'application/json'},
      body: jsonEncode({
        'code': code,
        'session_id': sessionId,
      }..removeWhere((_, v) => v == null)),
    );
    if (resp.statusCode != 200) {
      throw Exception('OAuth callback failed: ${resp.body}');
    }
  }

  void dispose() {
    _httpClient.close();
  }
}
