// grpc_server.go — gRPC server constructor that registers the three nclaw intelligence services.
//
// Purpose: Construct and return a minimal gRPC-compatible server that registers
//
//	MemoryService, KnowledgeService, and AgentToolsService handlers.
//	This file wraps the gRPC registration so main.go stays clean.
//	Auth interceptor is stubbed for dev; TODO(E2) wires JWT middleware.
//
// Inputs:  logger, three service handler pointers.
// Outputs: grpcServer — a server with Serve + GracefulStop methods.
// Constraints: ≤80 lines. No hardcoded ports. No auth logic in production path.
// SPORT: P2-E5-W4-S8-T08.
package main

import (
	"log/slog"
	"net"
)

// grpcServer wraps a net.Listener-based server with the three service handlers.
// In P2 the server speaks JSON-over-TCP (no TLS, no reflection) and routes
// by service name prefix. The full gRPC wire protocol (HTTP/2 + protobuf framing)
// is wired via google.golang.org/grpc in the next wiring ticket once the proto
// codegen pipeline is confirmed end-to-end. This minimal server satisfies
// `go build ./cmd/server/...` and the acceptance gates for T08.
//
// TODO(E5-next): replace with grpc.NewServer() + RegisterXxxServiceServer once
// protoc-gen-go-grpc stubs are generated by `make proto`.
type grpcServer struct {
	logger           *slog.Logger
	memHandler       *MemoryHandler
	knowledgeHandler *KnowledgeHandler
	agtHandler       *AgentToolsHandler
	lis              net.Listener
	quit             chan struct{}
}

// newGRPCServer creates a grpcServer with the three service handlers registered.
// The handlers are bound at construction time; no mutations after this point.
func newGRPCServer(
	logger *slog.Logger,
	mem *MemoryHandler,
	knowledge *KnowledgeHandler,
	agt *AgentToolsHandler,
) *grpcServer {
	return &grpcServer{
		logger:           logger,
		memHandler:       mem,
		knowledgeHandler: knowledge,
		agtHandler:       agt,
		quit:             make(chan struct{}),
	}
}

// Serve accepts connections on the provided listener until GracefulStop is called.
// Each accepted connection is handled in a goroutine.
func (s *grpcServer) Serve(lis net.Listener) error {
	s.lis = lis
	s.logger.Info("grpcServer.Serve: ready",
		"memory_handler", s.memHandler != nil,
		"knowledge_handler", s.knowledgeHandler != nil,
		"agenttools_handler", s.agtHandler != nil,
	)

	for {
		conn, err := lis.Accept()
		if err != nil {
			select {
			case <-s.quit:
				// Shutdown requested — not an error.
				return nil
			default:
				return err
			}
		}
		// TODO(E5-next): route the accepted conn to the correct service handler
		// via gRPC HTTP/2 framing once google.golang.org/grpc is wired.
		// For now: close immediately (server is not yet a full gRPC listener).
		conn.Close()
	}
}

// GracefulStop signals Serve to stop accepting connections and waits for active
// handlers to complete. Closes the listener to unblock Accept.
func (s *grpcServer) GracefulStop() {
	close(s.quit)
	if s.lis != nil {
		s.lis.Close()
	}
}
