//! libnclaw - shared types, protocol, E2E encryption, and plugin registry for nClaw clients

pub mod api;
pub mod backend;
pub mod bridge;
pub mod benchmark;
pub mod db;
pub mod crypto;
pub mod device;
pub mod error;
pub mod llm;
pub mod logging;
pub mod mobile_ffi;
pub mod models;
pub mod plugin;
pub mod protocol;
pub mod registry;
pub mod testing;
pub mod tier;
pub mod types;

// Re-export cache module for convenience
pub use models::cache;

// =============================================================================
// C FFI surface
//
// Minimal #[no_mangle] extern "C" exports so Swift, Kotlin, and TypeScript WASM
// stubs can link against libnclaw via cdylib / staticlib (see Cargo.toml).
// Header generated by: cbindgen --config cbindgen.toml --crate libnclaw -o libnclaw.h
//
// Design constraints:
//   - Only primitive / opaque-pointer types cross the boundary.
//   - Strings pass as null-terminated C strings (caller frees via libnclaw_free_string).
//   - All structs are kept on the Rust side; clients receive opaque Box<T> pointers.
//   - Error returns: NULL ptr on failure; call libnclaw_last_error() for a description.
// =============================================================================

use std::ffi::{CStr, CString};
use std::os::raw::c_char;
use std::ptr;

thread_local! {
    static LAST_ERROR: std::cell::RefCell<Option<CString>> = const { std::cell::RefCell::new(None) };
}

fn set_last_error(msg: &str) {
    LAST_ERROR.with(|e| {
        *e.borrow_mut() = CString::new(msg).ok();
    });
}

/// Return the last error message from any FFI call, or NULL if no error.
/// The returned pointer is valid until the next FFI call. Do NOT free it.
#[no_mangle]
pub extern "C" fn libnclaw_last_error() -> *const c_char {
    LAST_ERROR.with(|e| {
        e.borrow()
            .as_ref()
            .map(|s| s.as_ptr())
            .unwrap_or(ptr::null())
    })
}

/// Return the library version string (semver). Caller must NOT free.
#[no_mangle]
pub extern "C" fn libnclaw_version() -> *const c_char {
    // Static lifetime — safe to return.
    c"0.1.0".as_ptr()
}

/// Free a string previously allocated by libnclaw (e.g. libnclaw_keypair_public_b64).
/// Passing NULL is a no-op.
///
/// # Safety
/// `ptr` must have been returned by a libnclaw function that documents it as caller-owned.
#[no_mangle]
pub unsafe extern "C" fn libnclaw_free_string(ptr: *mut c_char) {
    if !ptr.is_null() {
        // Reconstruct and immediately drop.
        let _ = unsafe { CString::from_raw(ptr) };
    }
}

// =============================================================================
// Crypto FFI — DeviceKeypair
// =============================================================================

/// Opaque handle to a DeviceKeypair.
pub struct FfiDeviceKeypair(crypto::DeviceKeypair);

/// Generate a new X25519 DeviceKeypair. Returns NULL on failure.
/// Caller owns the returned pointer; free with libnclaw_keypair_free.
#[no_mangle]
pub extern "C" fn libnclaw_keypair_generate() -> *mut FfiDeviceKeypair {
    let kp = crypto::DeviceKeypair::generate();
    Box::into_raw(Box::new(FfiDeviceKeypair(kp)))
}

/// Return the base64-encoded public key of a DeviceKeypair.
/// Caller owns the returned string; free with libnclaw_free_string.
///
/// # Safety
/// `kp` must be a valid pointer returned by libnclaw_keypair_generate.
#[no_mangle]
pub unsafe extern "C" fn libnclaw_keypair_public_b64(kp: *const FfiDeviceKeypair) -> *mut c_char {
    if kp.is_null() {
        set_last_error("null keypair pointer");
        return ptr::null_mut();
    }
    let b64 = unsafe { (*kp).0.public_key_b64() };
    match CString::new(b64) {
        Ok(s) => s.into_raw(),
        Err(e) => {
            set_last_error(&e.to_string());
            ptr::null_mut()
        }
    }
}

/// Free a DeviceKeypair previously returned by libnclaw_keypair_generate.
/// Passing NULL is a no-op.
///
/// # Safety
/// `kp` must have been returned by libnclaw_keypair_generate and not yet freed.
#[no_mangle]
pub unsafe extern "C" fn libnclaw_keypair_free(kp: *mut FfiDeviceKeypair) {
    if !kp.is_null() {
        let _ = unsafe { Box::from_raw(kp) };
    }
}

// =============================================================================
// Crypto FFI — SessionCipher
// =============================================================================

/// Opaque handle to a SessionCipher (derived from a completed DH exchange).
pub struct FfiSessionCipher(crypto::SessionCipher);

/// Perform X25519 DH with `remote_pub_b64` using `kp` and return a SessionCipher.
/// Returns NULL on failure; check libnclaw_last_error().
/// Caller owns the returned pointer; free with libnclaw_cipher_free.
///
/// # Safety
/// `kp` and `remote_pub_b64` must be valid pointers.
#[no_mangle]
pub unsafe extern "C" fn libnclaw_keypair_dh(
    kp: *const FfiDeviceKeypair,
    remote_pub_b64: *const c_char,
) -> *mut FfiSessionCipher {
    if kp.is_null() || remote_pub_b64.is_null() {
        set_last_error("null argument");
        return ptr::null_mut();
    }
    let remote_str = match unsafe { CStr::from_ptr(remote_pub_b64) }.to_str() {
        Ok(s) => s,
        Err(e) => {
            set_last_error(&e.to_string());
            return ptr::null_mut();
        }
    };
    match unsafe { (*kp).0.diffie_hellman(remote_str) } {
        Ok(cipher) => Box::into_raw(Box::new(FfiSessionCipher(cipher))),
        Err(e) => {
            set_last_error(&e.to_string());
            ptr::null_mut()
        }
    }
}

/// Encrypt `plaintext` (null-terminated UTF-8) using `cipher`.
/// Returns the wire string (caller-owned; free with libnclaw_free_string), or NULL.
///
/// # Safety
/// Both pointers must be valid.
#[no_mangle]
pub unsafe extern "C" fn libnclaw_cipher_encrypt(
    cipher: *const FfiSessionCipher,
    plaintext: *const c_char,
) -> *mut c_char {
    if cipher.is_null() || plaintext.is_null() {
        set_last_error("null argument");
        return ptr::null_mut();
    }
    let pt = match unsafe { CStr::from_ptr(plaintext) }.to_str() {
        Ok(s) => s,
        Err(e) => {
            set_last_error(&e.to_string());
            return ptr::null_mut();
        }
    };
    match unsafe { (*cipher).0.encrypt_str(pt) } {
        Ok(wire) => match CString::new(wire) {
            Ok(s) => s.into_raw(),
            Err(e) => {
                set_last_error(&e.to_string());
                ptr::null_mut()
            }
        },
        Err(e) => {
            set_last_error(&e.to_string());
            ptr::null_mut()
        }
    }
}

/// Decrypt a wire string (null-terminated) using `cipher`.
/// Returns decrypted UTF-8 string (caller-owned; free with libnclaw_free_string), or NULL.
///
/// # Safety
/// Both pointers must be valid.
#[no_mangle]
pub unsafe extern "C" fn libnclaw_cipher_decrypt(
    cipher: *const FfiSessionCipher,
    wire: *const c_char,
) -> *mut c_char {
    if cipher.is_null() || wire.is_null() {
        set_last_error("null argument");
        return ptr::null_mut();
    }
    let wire_str = match unsafe { CStr::from_ptr(wire) }.to_str() {
        Ok(s) => s,
        Err(e) => {
            set_last_error(&e.to_string());
            return ptr::null_mut();
        }
    };
    match unsafe { (*cipher).0.decrypt_str(wire_str) } {
        Ok(pt) => match CString::new(pt) {
            Ok(s) => s.into_raw(),
            Err(e) => {
                set_last_error(&e.to_string());
                ptr::null_mut()
            }
        },
        Err(e) => {
            set_last_error(&e.to_string());
            ptr::null_mut()
        }
    }
}

/// Free a SessionCipher previously returned by libnclaw_keypair_dh.
/// Passing NULL is a no-op.
///
/// # Safety
/// `cipher` must have been returned by libnclaw_keypair_dh and not yet freed.
#[no_mangle]
pub unsafe extern "C" fn libnclaw_cipher_free(cipher: *mut FfiSessionCipher) {
    if !cipher.is_null() {
        let _ = unsafe { Box::from_raw(cipher) };
    }
}
