#!/bin/sh
set -e

# Install desktop file and update desktop database
if [ -x /usr/bin/update-desktop-database ]; then
    update-desktop-database /usr/share/applications || true
fi

# Update MIME type database
if [ -x /usr/bin/update-mime-database ]; then
    update-mime-database /usr/share/mime || true
fi

# Update icon cache
if [ -x /usr/bin/gtk-update-icon-cache ]; then
    gtk-update-icon-cache -f -t /usr/share/icons/hicolor || true
fi
