/// PLACEHOLDER — regenerated by `make codegen` (S20.T01).
/// Mirrors nclaw/core/src/types.rs.
library nclaw.rust.api.types;

class Message {
  final String id;
  final String conversationId;
  final String role;
  final String content;
  final DateTime createdAt;

  Message({
    required this.id,
    required this.conversationId,
    required this.role,
    required this.content,
    required this.createdAt,
  });

  factory Message.fromJson(Map<String, dynamic> json) => Message(
    id: json['id'] as String,
    conversationId: json['conversation_id'] as String,
    role: json['role'] as String,
    content: json['content'] as String,
    createdAt: DateTime.parse(json['created_at'] as String),
  );

  Map<String, dynamic> toJson() => {
    'id': id,
    'conversation_id': conversationId,
    'role': role,
    'content': content,
    'created_at': createdAt.toIso8601String(),
  };
}

class Topic {
  final String id;
  final String path;
  final String name;
  final bool archived;

  Topic({
    required this.id,
    required this.path,
    required this.name,
    this.archived = false,
  });

  factory Topic.fromJson(Map<String, dynamic> json) => Topic(
    id: json['id'] as String,
    path: json['path'] as String,
    name: json['name'] as String,
    archived: (json['archived'] as bool?) ?? false,
  );

  Map<String, dynamic> toJson() => {
    'id': id,
    'path': path,
    'name': name,
    'archived': archived,
  };
}

class Memory {
  final String id;
  final String content;
  final double confidence;

  Memory({
    required this.id,
    required this.content,
    required this.confidence,
  });

  factory Memory.fromJson(Map<String, dynamic> json) => Memory(
    id: json['id'] as String,
    content: json['content'] as String,
    confidence: (json['confidence'] as num).toDouble(),
  );

  Map<String, dynamic> toJson() => {
    'id': id,
    'content': content,
    'confidence': confidence,
  };
}
