/* libnclaw.h — C FFI surface for libnclaw (Rust core).
 *
 * AUTO-GENERATED BY cbindgen — DO NOT EDIT BY HAND.
 * Regenerate with:
 *   cbindgen --config cbindgen.toml --crate libnclaw -o core/include/libnclaw.h
 *
 * This file provides the minimal C declarations needed by:
 *   - iOS Swift callers (via -lnclaw.a inside the .xcframework)
 *   - Android JNI callers (via libnclaw.so in jniLibs)
 *
 * All memory-owning types are opaque pointers. Callers must use the
 * corresponding _free functions. Never pass a pointer to a freed object.
 */

#pragma once

#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* -------------------------------------------------------------------------
 * Error handling
 * ---------------------------------------------------------------------- */

/** Return the last error message (UTF-8, null-terminated) or NULL if none.
 *  Valid until the next FFI call on the same thread. Do NOT free. */
const char *libnclaw_last_error(void);

/** Return the semver version string. Never NULL. Do NOT free. */
const char *libnclaw_version(void);

/** Free a string previously returned by a libnclaw function that documents
 *  it as caller-owned. Passing NULL is a no-op. */
void libnclaw_free_string(char *ptr);

/* -------------------------------------------------------------------------
 * Crypto — DeviceKeypair
 * ---------------------------------------------------------------------- */

/** Opaque handle to an X25519 DeviceKeypair. */
typedef struct FfiDeviceKeypair FfiDeviceKeypair;

/** Generate a new X25519 keypair. Returns NULL on failure. Caller owns;
 *  free with libnclaw_keypair_free. */
FfiDeviceKeypair *libnclaw_keypair_generate(void);

/** Return the base64-encoded public key. Caller owns string;
 *  free with libnclaw_free_string. */
char *libnclaw_keypair_public_b64(const FfiDeviceKeypair *kp);

/** Free a DeviceKeypair. Passing NULL is a no-op. */
void libnclaw_keypair_free(FfiDeviceKeypair *kp);

/* -------------------------------------------------------------------------
 * Crypto — SessionCipher
 * ---------------------------------------------------------------------- */

/** Opaque handle to a derived SessionCipher (XChaCha20-Poly1305). */
typedef struct FfiSessionCipher FfiSessionCipher;

/** Perform X25519 DH with remote_pub_b64 using kp. Returns NULL on failure.
 *  Caller owns; free with libnclaw_cipher_free. */
FfiSessionCipher *libnclaw_keypair_dh(const FfiDeviceKeypair *kp,
                                       const char *remote_pub_b64);

/** Encrypt plaintext (null-terminated UTF-8). Returns wire string (caller-owned;
 *  free with libnclaw_free_string), or NULL on error. */
char *libnclaw_cipher_encrypt(const FfiSessionCipher *cipher,
                               const char *plaintext);

/** Decrypt a wire string. Returns plaintext (caller-owned;
 *  free with libnclaw_free_string), or NULL on error. */
char *libnclaw_cipher_decrypt(const FfiSessionCipher *cipher,
                               const char *wire);

/** Free a SessionCipher. Passing NULL is a no-op. */
void libnclaw_cipher_free(FfiSessionCipher *cipher);

/* -------------------------------------------------------------------------
 * Mobile dampers — battery, low-power, thermal
 *
 * Call these from the platform layer (Swift / Kotlin) whenever the OS
 * notifies of a power-state or thermal-state change. Thread-safe;
 * backed by atomics in Rust. Available on iOS and Android only
 * (compiled out on other targets).
 * ---------------------------------------------------------------------- */

/** Notify libnclaw that iOS/Android Low Power Mode is on (true) or off (false).
 *  When on, the tier classifier drops one tier to reduce inference load. */
void nclaw_set_low_power(bool flag);

/** Notify libnclaw of the current battery percentage (0–100).
 *  When below the configured threshold and not charging, local LLM inference
 *  is suspended to preserve battery. */
void nclaw_set_battery_pct(uint8_t pct);

/** Notify libnclaw of the current thermal pressure level:
 *    0 = nominal  — no throttle
 *    1 = fair     — no throttle
 *    2 = serious  — 50 ms inter-token delay injected into streaming
 *    3 = critical — 200 ms inter-token delay injected into streaming
 *  Values above 3 are clamped to 3. */
void nclaw_set_thermal_level(uint8_t level);

#ifdef __cplusplus
} /* extern "C" */
#endif
