//! Ollama sidecar backend — full implementation with auto-detect, chat streaming, and embeddings.
//!
//! Connects to a locally running Ollama instance (default: http://localhost:11434).
//! Supports streaming chat completions, embedding generation, and automatic instance detection.
//!
//! # Example
//! ```no_run
//! use libnclaw::llm::OllamaBackend;
//! # tokio::runtime::Runtime::new().unwrap().block_on(async {
//! if let Some(backend) = OllamaBackend::auto_detect().await {
//!     let models = backend.list_models().await.unwrap();
//!     println!("Available models: {:?}", models);
//! }
//! # });
//! ```

use serde::{Deserialize, Serialize};
use std::time::Duration;
use tokio_stream::StreamExt;

use crate::error::LlmError;

/// OllamaBackend provides an interface to a local Ollama instance.
#[derive(Clone)]
pub struct OllamaBackend {
    base_url: String,
    client: reqwest::Client,
}

impl OllamaBackend {
    /// Create a new OllamaBackend pointing to the given base URL.
    ///
    /// # Arguments
    /// * `base_url` - The base URL of the Ollama API (e.g., "http://localhost:11434")
    ///
    /// # Example
    /// ```no_run
    /// use libnclaw::llm::OllamaBackend;
    /// let backend = OllamaBackend::new("http://localhost:11434");
    /// ```
    pub fn new(base_url: impl Into<String>) -> Self {
        Self {
            base_url: base_url.into(),
            client: reqwest::Client::new(),
        }
    }

    /// Auto-detect a running Ollama instance on localhost:11434.
    ///
    /// Returns `Some(backend)` if Ollama is reachable within 500ms, `None` otherwise.
    /// Fails silently on network errors — no panic, no logging.
    ///
    /// # Example
    /// ```no_run
    /// use libnclaw::llm::OllamaBackend;
    /// # tokio::runtime::Runtime::new().unwrap().block_on(async {
    /// match OllamaBackend::auto_detect().await {
    ///     Some(b) => println!("Ollama found"),
    ///     None => println!("Ollama not running"),
    /// }
    /// # });
    /// ```
    pub async fn auto_detect() -> Option<Self> {
        let backend = Self::new("http://localhost:11434");
        match tokio::time::timeout(
            Duration::from_millis(500),
            backend.client.get(format!("{}/api/tags", backend.base_url)).send(),
        )
        .await
        {
            Ok(Ok(resp)) if resp.status().is_success() => Some(backend),
            _ => None,
        }
    }

    /// List all available models on the Ollama instance.
    ///
    /// # Returns
    /// A vector of available models with metadata (name, size, modified time).
    ///
    /// # Errors
    /// Returns `LlmError::ProviderUnreachable` if Ollama is not accessible.
    pub async fn list_models(&self) -> Result<Vec<OllamaModel>, LlmError> {
        let url = format!("{}/api/tags", self.base_url);
        let resp: OllamaTagsResponse = self
            .client
            .get(&url)
            .send()
            .await
            .map_err(|e| LlmError::ProviderUnreachable(e.to_string()))?
            .json()
            .await
            .map_err(|e| LlmError::ProviderUnreachable(e.to_string()))?;
        Ok(resp.models)
    }

    /// Stream a chat completion from Ollama.
    ///
    /// Streams tokens as they are generated by the model. Each token is yielded
    /// as a separate item in the stream.
    ///
    /// # Arguments
    /// * `model` - The model name (e.g., "llama2", "neural-chat")
    /// * `messages` - A slice of message objects with role and content
    ///
    /// # Returns
    /// A stream of token strings, or an error if the request fails.
    ///
    /// # Example
    /// ```no_run
    /// use libnclaw::llm::{OllamaBackend, OllamaMessage};
    /// use tokio_stream::StreamExt;
    /// # tokio::runtime::Runtime::new().unwrap().block_on(async {
    /// let backend = OllamaBackend::new("http://localhost:11434");
    /// let msgs = vec![
    ///     OllamaMessage { role: "user".into(), content: "Hello!".into() }
    /// ];
    /// let mut stream = backend.chat_stream("llama2", &msgs).await.unwrap();
    /// while let Some(Ok(token)) = stream.next().await {
    ///     print!("{}", token);
    /// }
    /// # });
    /// ```
    pub async fn chat_stream(
        &self,
        model: &str,
        messages: &[OllamaMessage],
    ) -> Result<impl tokio_stream::Stream<Item = Result<String, LlmError>>, LlmError> {
        let url = format!("{}/api/chat", self.base_url);
        let body = serde_json::json!({
            "model": model,
            "messages": messages,
            "stream": true,
        });

        let response = self
            .client
            .post(&url)
            .json(&body)
            .send()
            .await
            .map_err(|e| LlmError::ProviderUnreachable(e.to_string()))?;

        if !response.status().is_success() {
            return Err(LlmError::InvalidResponse(format!(
                "HTTP {}",
                response.status()
            )));
        }

        let stream = response.bytes_stream();

        // Use async_stream to parse NDJSON and yield tokens
        Ok(async_stream::stream! {
            let mut stream = stream;
            while let Some(chunk_result) = stream.next().await {
                match chunk_result {
                    Ok(bytes) => {
                        let text = String::from_utf8_lossy(&bytes);
                        for line in text.lines() {
                            if let Ok(chunk) = serde_json::from_str::<OllamaChatChunk>(line) {
                                if let Some(msg) = chunk.message {
                                    if !msg.content.is_empty() {
                                        yield Ok(msg.content);
                                    }
                                }
                                if chunk.done {
                                    return;
                                }
                            }
                        }
                    }
                    Err(e) => {
                        yield Err(LlmError::ProviderUnreachable(e.to_string()));
                        return;
                    }
                }
            }
        })
    }

    /// Generate embeddings for a given text prompt.
    ///
    /// # Arguments
    /// * `model` - The embedding model name (e.g., "nomic-embed-text")
    /// * `prompt` - The text to embed
    ///
    /// # Returns
    /// A vector of f32 values representing the embedding.
    ///
    /// # Errors
    /// Returns `LlmError::ProviderUnreachable` if Ollama is not accessible.
    pub async fn embed(&self, model: &str, prompt: &str) -> Result<Vec<f32>, LlmError> {
        let url = format!("{}/api/embeddings", self.base_url);
        let body = serde_json::json!({
            "model": model,
            "prompt": prompt,
        });

        let resp: OllamaEmbedResponse = self
            .client
            .post(&url)
            .json(&body)
            .send()
            .await
            .map_err(|e| LlmError::ProviderUnreachable(e.to_string()))?
            .json()
            .await
            .map_err(|e| LlmError::ProviderUnreachable(e.to_string()))?;

        Ok(resp.embedding)
    }
}

/// Response from /api/tags listing available models.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OllamaTagsResponse {
    pub models: Vec<OllamaModel>,
}

/// A single model available on the Ollama instance.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OllamaModel {
    pub name: String,
    pub size: u64,
    pub modified_at: String,
}

/// A chat message for /api/chat requests.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OllamaMessage {
    pub role: String,
    pub content: String,
}

/// A single chunk from the /api/chat stream (NDJSON format).
#[derive(Debug, Clone, Serialize, Deserialize)]
struct OllamaChatChunk {
    pub message: Option<OllamaMessage>,
    pub done: bool,
}

/// Response from /api/embeddings.
#[derive(Debug, Clone, Serialize, Deserialize)]
struct OllamaEmbedResponse {
    pub embedding: Vec<f32>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_ollama_backend_new() {
        let backend = OllamaBackend::new("http://localhost:11434");
        assert_eq!(backend.base_url, "http://localhost:11434");
    }

    #[test]
    fn test_ollama_message_serialize() {
        let msg = OllamaMessage {
            role: "user".into(),
            content: "Hello".into(),
        };
        let json = serde_json::to_string(&msg).unwrap();
        assert!(json.contains("\"role\":\"user\""));
    }

    #[test]
    fn test_ollama_model_serialize() {
        let model = OllamaModel {
            name: "llama2".into(),
            size: 3791621160,
            modified_at: "2024-01-15T12:00:00Z".into(),
        };
        let json = serde_json::to_string(&model).unwrap();
        assert!(json.contains("\"name\":\"llama2\""));
    }
}
