import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:mobile_scanner/mobile_scanner.dart';

import '../models/server_config.dart';
import '../providers/connection_provider.dart';
import '../services/auth_service.dart';
import '../services/deep_link_service.dart';

/// Screen for pairing with a self-hosted nSelf server running the nself-claw plugin.
///
/// Two tabs:
///   - Sign in: classic email + password flow against Hasura Auth
///   - Pair with code: enter a 6-char short code generated by nclaw CLI or /pair TG command
class PairingScreen extends ConsumerStatefulWidget {
  const PairingScreen({super.key});

  @override
  ConsumerState<PairingScreen> createState() => _PairingScreenState();
}

class _PairingScreenState extends ConsumerState<PairingScreen>
    with SingleTickerProviderStateMixin {
  late final TabController _tabController;
  final _authService = AuthService();

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 3, vsync: this);
  }

  @override
  void dispose() {
    _tabController.dispose();
    _authService.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Scaffold(
      body: SafeArea(
        child: Column(
          children: [
            const SizedBox(height: 40),
            Icon(Icons.link, size: 56, color: theme.colorScheme.primary),
            const SizedBox(height: 16),
            Text('Connect to your server', style: theme.textTheme.headlineSmall),
            const SizedBox(height: 24),
            TabBar(
              controller: _tabController,
              tabs: const [
                Tab(icon: Icon(Icons.qr_code_scanner, size: 20), text: 'Scan QR'),
                Tab(icon: Icon(Icons.pin, size: 20), text: 'Enter Code'),
                Tab(icon: Icon(Icons.link, size: 20), text: 'Direct URL'),
              ],
            ),
            Expanded(
              child: TabBarView(
                controller: _tabController,
                children: [
                  _ScanQrTab(authService: _authService, tabController: _tabController),
                  _PairWithCodeTab(authService: _authService),
                  _SignInTab(authService: _authService),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}

// =============================================================================
// Tab 1 — Scan QR
// =============================================================================

class _ScanQrTab extends ConsumerStatefulWidget {
  final AuthService authService;
  final TabController tabController;
  const _ScanQrTab({required this.authService, required this.tabController});

  @override
  ConsumerState<_ScanQrTab> createState() => _ScanQrTabState();
}

class _ScanQrTabState extends ConsumerState<_ScanQrTab> {
  bool _scanned = false;

  void _handleDetect(BarcodeCapture capture) {
    if (_scanned) return;
    final barcode = capture.barcodes.firstOrNull;
    final value = barcode?.rawValue;
    if (value == null) return;

    final uri = Uri.tryParse(value);
    if (uri != null && uri.scheme == 'nclaw' && uri.host == 'pair') {
      final server = uri.queryParameters['server'];
      final code = uri.queryParameters['code'];
      if (server != null && code != null) {
        setState(() => _scanned = true);
        ref.read(pendingPairProvider.notifier).state =
            PairParams(serverUrl: server, code: code.toUpperCase());
        // Switch to the Enter Code tab to complete pairing.
        widget.tabController.animateTo(1);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Column(
      children: [
        const SizedBox(height: 16),
        Text(
          'Point your camera at the QR code shown by nclaw.',
          textAlign: TextAlign.center,
          style: theme.textTheme.bodyMedium?.copyWith(
            color: theme.colorScheme.onSurface.withValues(alpha: 0.7),
          ),
        ),
        const SizedBox(height: 16),
        Expanded(
          child: ClipRRect(
            borderRadius: BorderRadius.circular(16),
            child: Padding(
              padding: const EdgeInsets.symmetric(horizontal: 32),
              child: ClipRRect(
                borderRadius: BorderRadius.circular(16),
                child: Stack(
                  children: [
                    MobileScanner(onDetect: _handleDetect),
                    if (_scanned)
                      Container(
                        color: Colors.black54,
                        child: Center(
                          child: Column(
                            mainAxisSize: MainAxisSize.min,
                            children: [
                              Icon(Icons.check_circle,
                                  size: 64, color: theme.colorScheme.primary),
                              const SizedBox(height: 12),
                              Text(
                                'Code scanned',
                                style: theme.textTheme.titleMedium?.copyWith(
                                  color: Colors.white,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                  ],
                ),
              ),
            ),
          ),
        ),
        const SizedBox(height: 16),
      ],
    );
  }
}

// =============================================================================
// Tab 2 — Sign in (email + password, "Direct URL")
// =============================================================================

class _SignInTab extends ConsumerStatefulWidget {
  final AuthService authService;
  const _SignInTab({required this.authService});

  @override
  ConsumerState<_SignInTab> createState() => _SignInTabState();
}

class _SignInTabState extends ConsumerState<_SignInTab> {
  final _urlController = TextEditingController();
  final _emailController = TextEditingController();
  final _passwordController = TextEditingController();
  final _nameController = TextEditingController();
  final _formKey = GlobalKey<FormState>();

  bool _pairing = false;
  String? _errorMessage;
  bool _obscurePassword = true;

  @override
  void dispose() {
    _urlController.dispose();
    _emailController.dispose();
    _passwordController.dispose();
    _nameController.dispose();
    super.dispose();
  }

  Future<void> _handleSignIn() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() {
      _pairing = true;
      _errorMessage = null;
    });

    final serverUrl = _urlController.text.trim();
    final email = _emailController.text.trim();
    final password = _passwordController.text;
    final serverName = _nameController.text.trim().isNotEmpty
        ? _nameController.text.trim()
        : Uri.parse(serverUrl).host;

    try {
      final result = await widget.authService.signIn(
        serverUrl: serverUrl,
        email: email,
        password: password,
      );

      final serverId =
          '${Uri.parse(serverUrl).host}_${result.userId}'.hashCode.toRadixString(16);

      final server = ServerConfig(
        id: serverId,
        url: serverUrl,
        name: serverName,
        jwtToken: result.accessToken,
        refreshToken: result.refreshToken,
      );

      await ref.read(connectionProvider.notifier).addServer(server);
    } on AuthException catch (e) {
      if (mounted) setState(() => _errorMessage = e.message);
    } catch (e) {
      if (mounted) {
        setState(() => _errorMessage = 'Connection failed. Check the server URL.');
      }
    } finally {
      if (mounted) setState(() => _pairing = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return SingleChildScrollView(
      padding: const EdgeInsets.symmetric(horizontal: 32),
      child: Form(
        key: _formKey,
        child: Column(
          children: [
            const SizedBox(height: 24),
            Text(
              'Enter your server URL and account credentials.',
              textAlign: TextAlign.center,
              style: theme.textTheme.bodyMedium?.copyWith(
                color: theme.colorScheme.onSurface.withValues(alpha: 0.7),
              ),
            ),
            const SizedBox(height: 24),
            TextFormField(
              controller: _urlController,
              keyboardType: TextInputType.url,
              autocorrect: false,
              textInputAction: TextInputAction.next,
              decoration: const InputDecoration(
                labelText: 'Server URL',
                hintText: 'https://api.example.com',
                border: OutlineInputBorder(),
                prefixIcon: Icon(Icons.dns),
              ),
              validator: (value) {
                if (value == null || value.trim().isEmpty) {
                  return 'Server URL is required';
                }
                final uri = Uri.tryParse(value.trim());
                if (uri == null || !uri.hasScheme || !uri.hasAuthority) {
                  return 'Enter a valid URL (e.g. https://api.example.com)';
                }
                return null;
              },
            ),
            const SizedBox(height: 16),
            TextFormField(
              controller: _nameController,
              textInputAction: TextInputAction.next,
              decoration: const InputDecoration(
                labelText: 'Server name (optional)',
                hintText: 'My Server',
                border: OutlineInputBorder(),
                prefixIcon: Icon(Icons.label_outline),
              ),
            ),
            const SizedBox(height: 16),
            TextFormField(
              controller: _emailController,
              keyboardType: TextInputType.emailAddress,
              autocorrect: false,
              textInputAction: TextInputAction.next,
              decoration: const InputDecoration(
                labelText: 'Email',
                border: OutlineInputBorder(),
                prefixIcon: Icon(Icons.email_outlined),
              ),
              validator: (value) {
                if (value == null || value.trim().isEmpty) return 'Email is required';
                if (!value.contains('@')) return 'Enter a valid email address';
                return null;
              },
            ),
            const SizedBox(height: 16),
            TextFormField(
              controller: _passwordController,
              obscureText: _obscurePassword,
              textInputAction: TextInputAction.done,
              onFieldSubmitted: (_) => _handleSignIn(),
              decoration: InputDecoration(
                labelText: 'Password',
                border: const OutlineInputBorder(),
                prefixIcon: const Icon(Icons.lock_outline),
                suffixIcon: IconButton(
                  icon: Icon(_obscurePassword
                      ? Icons.visibility_off
                      : Icons.visibility),
                  onPressed: () =>
                      setState(() => _obscurePassword = !_obscurePassword),
                ),
              ),
              validator: (value) {
                if (value == null || value.isEmpty) return 'Password is required';
                return null;
              },
            ),
            const SizedBox(height: 8),
            if (_errorMessage != null) ...[
              const SizedBox(height: 8),
              _ErrorBox(message: _errorMessage!),
            ],
            const SizedBox(height: 24),
            SizedBox(
              width: double.infinity,
              child: FilledButton(
                onPressed: _pairing ? null : _handleSignIn,
                child: _pairing
                    ? const SizedBox(
                        height: 20,
                        width: 20,
                        child: CircularProgressIndicator(strokeWidth: 2),
                      )
                    : const Text('Sign in'),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

// =============================================================================
// Tab 3 — Pair with code (6-char short code from nclaw CLI or /pair TG command)
// =============================================================================

/// Two-step flow:
///   Step 1 — Enter server URL + 6-char code → verify code → get user_id
///   Step 2 — Enter password to complete sign-in (Hasura Auth JWT)
class _PairWithCodeTab extends ConsumerStatefulWidget {
  final AuthService authService;
  const _PairWithCodeTab({required this.authService});

  @override
  ConsumerState<_PairWithCodeTab> createState() => _PairWithCodeTabState();
}

class _PairWithCodeTabState extends ConsumerState<_PairWithCodeTab> {
  // Step 1 — code verification
  final _urlController = TextEditingController();
  final _codeController = TextEditingController();
  final _step1FormKey = GlobalKey<FormState>();

  // Step 2 — password sign-in
  final _emailController = TextEditingController();
  final _passwordController = TextEditingController();
  final _step2FormKey = GlobalKey<FormState>();
  bool _obscurePassword = true;

  bool _verifying = false;
  bool _connecting = false;
  String? _errorMessage;

  /// Non-null when step 1 completes — the verified user_id from the server.
  String? _verifiedUserId;

  @override
  void initState() {
    super.initState();
    // Pre-fill from a deep link or QR scan that arrived before this tab opened.
    WidgetsBinding.instance.addPostFrameCallback((_) {
      final pending = ref.read(pendingPairProvider);
      if (pending != null && mounted) {
        _urlController.text = pending.serverUrl;
        _codeController.text = pending.code;
        ref.read(pendingPairProvider.notifier).state = null;
      }
    });
  }

  @override
  void dispose() {
    _urlController.dispose();
    _codeController.dispose();
    _emailController.dispose();
    _passwordController.dispose();
    super.dispose();
  }

  Future<void> _handleVerify() async {
    if (!_step1FormKey.currentState!.validate()) return;

    setState(() {
      _verifying = true;
      _errorMessage = null;
    });

    try {
      final userId = await widget.authService.redeemPairCode(
        serverUrl: _urlController.text.trim(),
        code: _codeController.text.trim(),
      );
      if (mounted) {
        setState(() {
          _verifiedUserId = userId;
          _verifying = false;
        });
      }
    } on AuthException catch (e) {
      if (mounted) {
        setState(() {
          _errorMessage = e.message;
          _verifying = false;
        });
      }
    } catch (e) {
      if (mounted) {
        setState(() {
          _errorMessage = 'Connection failed. Check the server URL.';
          _verifying = false;
        });
      }
    }
  }

  Future<void> _handleConnect() async {
    if (!_step2FormKey.currentState!.validate()) return;

    setState(() {
      _connecting = true;
      _errorMessage = null;
    });

    final serverUrl = _urlController.text.trim();
    final email = _emailController.text.trim();
    final password = _passwordController.text;
    final serverName = Uri.parse(serverUrl).host;

    try {
      final result = await widget.authService.signIn(
        serverUrl: serverUrl,
        email: email,
        password: password,
      );

      final serverId =
          '${Uri.parse(serverUrl).host}_${result.userId}'.hashCode.toRadixString(16);

      final server = ServerConfig(
        id: serverId,
        url: serverUrl,
        name: serverName,
        jwtToken: result.accessToken,
        refreshToken: result.refreshToken,
      );

      await ref.read(connectionProvider.notifier).addServer(server);
    } on AuthException catch (e) {
      if (mounted) setState(() => _errorMessage = e.message);
    } catch (e) {
      if (mounted) {
        setState(
            () => _errorMessage = 'Sign-in failed. Check your email and password.');
      }
    } finally {
      if (mounted) setState(() => _connecting = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    if (_verifiedUserId == null) {
      return _buildStep1(context);
    }
    return _buildStep2(context);
  }

  Widget _buildStep1(BuildContext context) {
    final theme = Theme.of(context);

    return SingleChildScrollView(
      padding: const EdgeInsets.symmetric(horizontal: 32),
      child: Form(
        key: _step1FormKey,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const SizedBox(height: 24),
            Text(
              'Enter the code shown by nclaw or sent via your Telegram bot.',
              textAlign: TextAlign.center,
              style: theme.textTheme.bodyMedium?.copyWith(
                color: theme.colorScheme.onSurface.withValues(alpha: 0.7),
              ),
            ),
            const SizedBox(height: 24),
            TextFormField(
              controller: _urlController,
              keyboardType: TextInputType.url,
              autocorrect: false,
              textInputAction: TextInputAction.next,
              decoration: const InputDecoration(
                labelText: 'Server URL',
                hintText: 'https://api.example.com',
                border: OutlineInputBorder(),
                prefixIcon: Icon(Icons.dns),
              ),
              validator: (value) {
                if (value == null || value.trim().isEmpty) {
                  return 'Server URL is required';
                }
                final uri = Uri.tryParse(value.trim());
                if (uri == null || !uri.hasScheme || !uri.hasAuthority) {
                  return 'Enter a valid URL';
                }
                return null;
              },
            ),
            const SizedBox(height: 16),
            TextFormField(
              controller: _codeController,
              autocorrect: false,
              textInputAction: TextInputAction.done,
              onFieldSubmitted: (_) => _handleVerify(),
              maxLength: 8,
              textCapitalization: TextCapitalization.characters,
              inputFormatters: [
                FilteringTextInputFormatter.allow(RegExp(r'[A-Za-z0-9]')),
                _UpperCaseTextFormatter(),
              ],
              style: theme.textTheme.headlineMedium?.copyWith(
                letterSpacing: 8,
                fontWeight: FontWeight.bold,
              ),
              textAlign: TextAlign.center,
              decoration: const InputDecoration(
                labelText: 'Pairing code',
                hintText: 'ABCDEF',
                border: OutlineInputBorder(),
                prefixIcon: Icon(Icons.pin),
                counterText: '',
              ),
              validator: (value) {
                if (value == null || value.trim().isEmpty) {
                  return 'Pairing code is required';
                }
                if (value.trim().length < 6) {
                  return 'Enter the full 6-character code';
                }
                return null;
              },
            ),
            if (_errorMessage != null) ...[
              const SizedBox(height: 8),
              _ErrorBox(message: _errorMessage!),
            ],
            const SizedBox(height: 24),
            SizedBox(
              width: double.infinity,
              child: FilledButton(
                onPressed: _verifying ? null : _handleVerify,
                child: _verifying
                    ? const SizedBox(
                        height: 20,
                        width: 20,
                        child: CircularProgressIndicator(strokeWidth: 2),
                      )
                    : const Text('Verify code'),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildStep2(BuildContext context) {
    final theme = Theme.of(context);

    return SingleChildScrollView(
      padding: const EdgeInsets.symmetric(horizontal: 32),
      child: Form(
        key: _step2FormKey,
        child: Column(
          children: [
            const SizedBox(height: 24),
            Container(
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                color: theme.colorScheme.primary.withValues(alpha: 0.1),
                borderRadius: BorderRadius.circular(8),
                border: Border.all(
                  color: theme.colorScheme.primary.withValues(alpha: 0.3),
                ),
              ),
              child: Row(
                children: [
                  Icon(Icons.check_circle_outline,
                      color: theme.colorScheme.primary),
                  const SizedBox(width: 12),
                  Expanded(
                    child: Text(
                      'Code verified! Enter your password to complete sign-in.',
                      style: theme.textTheme.bodySmall?.copyWith(
                        color: theme.colorScheme.primary,
                      ),
                    ),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 24),
            TextFormField(
              controller: _emailController,
              keyboardType: TextInputType.emailAddress,
              autocorrect: false,
              textInputAction: TextInputAction.next,
              decoration: const InputDecoration(
                labelText: 'Email',
                border: OutlineInputBorder(),
                prefixIcon: Icon(Icons.email_outlined),
              ),
              validator: (value) {
                if (value == null || value.trim().isEmpty) return 'Email is required';
                if (!value.contains('@')) return 'Enter a valid email address';
                return null;
              },
            ),
            const SizedBox(height: 16),
            TextFormField(
              controller: _passwordController,
              obscureText: _obscurePassword,
              textInputAction: TextInputAction.done,
              onFieldSubmitted: (_) => _handleConnect(),
              decoration: InputDecoration(
                labelText: 'Password',
                border: const OutlineInputBorder(),
                prefixIcon: const Icon(Icons.lock_outline),
                suffixIcon: IconButton(
                  icon: Icon(_obscurePassword
                      ? Icons.visibility_off
                      : Icons.visibility),
                  onPressed: () =>
                      setState(() => _obscurePassword = !_obscurePassword),
                ),
              ),
              validator: (value) {
                if (value == null || value.isEmpty) return 'Password is required';
                return null;
              },
            ),
            const SizedBox(height: 8),
            if (_errorMessage != null) ...[
              const SizedBox(height: 8),
              _ErrorBox(message: _errorMessage!),
            ],
            const SizedBox(height: 24),
            SizedBox(
              width: double.infinity,
              child: FilledButton(
                onPressed: _connecting ? null : _handleConnect,
                child: _connecting
                    ? const SizedBox(
                        height: 20,
                        width: 20,
                        child: CircularProgressIndicator(strokeWidth: 2),
                      )
                    : const Text('Connect'),
              ),
            ),
            const SizedBox(height: 12),
            TextButton(
              onPressed: () => setState(() {
                _verifiedUserId = null;
                _errorMessage = null;
              }),
              child: const Text('Use a different code'),
            ),
          ],
        ),
      ),
    );
  }
}

// =============================================================================
// Shared widgets
// =============================================================================

class _ErrorBox extends StatelessWidget {
  final String message;
  const _ErrorBox({required this.message});

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: theme.colorScheme.error.withValues(alpha: 0.1),
        borderRadius: BorderRadius.circular(8),
        border: Border.all(
          color: theme.colorScheme.error.withValues(alpha: 0.3),
        ),
      ),
      child: Text(
        message,
        style: theme.textTheme.bodySmall?.copyWith(
          color: theme.colorScheme.error,
        ),
      ),
    );
  }
}

/// Input formatter that forces all text to uppercase.
class _UpperCaseTextFormatter extends TextInputFormatter {
  @override
  TextEditingValue formatEditUpdate(
    TextEditingValue oldValue,
    TextEditingValue newValue,
  ) {
    return newValue.copyWith(text: newValue.text.toUpperCase());
  }
}

// QR scanning is now handled inline by _ScanQrTab above.
