#!/bin/bash
# Generate auto-update feed files for all desktop platforms
# Run after building release artifacts
set -euo pipefail

VERSION="${1:?Usage: generate-update-feeds.sh <version>}"
BASE_URL="https://downloads.nself.org/claw"
OUTPUT_DIR="${2:-build/update-feeds}"

mkdir -p "$OUTPUT_DIR/macos" "$OUTPUT_DIR/linux" "$OUTPUT_DIR/windows"

# --- macOS: Sparkle appcast.xml ---
# Note: Full appcast generation requires `generate_appcast` from Sparkle framework
# with the ed25519 private key. This produces the skeleton; run generate_appcast
# on the DMG directory for the real feed.
cat > "$OUTPUT_DIR/macos/appcast.xml" << APPCAST
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>ɳClaw Updates</title>
    <link>${BASE_URL}/macos/appcast.xml</link>
    <description>Most recent updates for ɳClaw</description>
    <language>en</language>
    <item>
      <title>Version ${VERSION}</title>
      <sparkle:version>${VERSION}</sparkle:version>
      <sparkle:shortVersionString>${VERSION}</sparkle:shortVersionString>
      <sparkle:minimumSystemVersion>12.0</sparkle:minimumSystemVersion>
      <pubDate>$(date -R)</pubDate>
      <enclosure
        url="${BASE_URL}/macos/Claw-${VERSION}.dmg"
        type="application/octet-stream"
        sparkle:edSignature="SIGNATURE_PLACEHOLDER"
        length="0"
      />
    </item>
  </channel>
</rss>
APPCAST
echo "Generated: $OUTPUT_DIR/macos/appcast.xml"

# --- Linux: latest.json ---
cat > "$OUTPUT_DIR/linux/latest.json" << LINUX
{
  "version": "${VERSION}",
  "url": "${BASE_URL}/linux/Claw-${VERSION}-x86_64.AppImage",
  "sha256": "",
  "release_date": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "release_notes": "https://github.com/nself-org/nclaw/releases/tag/v${VERSION}"
}
LINUX
echo "Generated: $OUTPUT_DIR/linux/latest.json"

# --- Windows: RELEASES (Squirrel format) ---
# Squirrel RELEASES file is generated by Squirrel.Windows tooling.
# This creates a placeholder. Real generation requires nuget + Squirrel CLI.
cat > "$OUTPUT_DIR/windows/RELEASES" << WIN
# Squirrel RELEASES file - generated by Squirrel.Windows tooling
# Placeholder - run 'Squirrel --releasify' to produce real deltas
WIN
echo "Generated: $OUTPUT_DIR/windows/RELEASES (placeholder)"

echo "Update feeds generated in $OUTPUT_DIR"
echo ""
echo "Next steps:"
echo "  macOS: Run 'generate_appcast' with Sparkle ed25519 private key on DMG directory"
echo "  Linux: Compute sha256 of AppImage and update latest.json"
echo "  Windows: Run 'Squirrel --releasify' to produce RELEASES + nupkg deltas"
